name: HideItem
version: ${project.version}
main: com.vomarek.hideitem.HideItem
authors: [1vomarek1]
commands:
  hideitem:
    description: "Default command of HideItem."
permissions:
  hideitem:
    "*":
      description: "All permissions of HideItem"
      default: op
      children:
        hideitem.admin: true
        hideitem.reload: true
        hideitem.show: true
        hideitem.hide: true
        hideitem.toggle: true
    admin:
      description: "Permission to use admin commands of HideItem"
      default: op
      children:
        hideitem.reload: true
    reload:
      description: "Permission to use admin commands of HideItem"
      default: op
    seevanished:
      description: "Permission to see vanished people after unhiding players"
    show:
      description: "Permission to use command to show all players"
    hide:
      description: "Permission to use command to hide all players"
    toggle:
      description: "Permission to use command to toggle all players"